version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
